### ISSUE TITLE
Landscape View then not proper working

### ISSUE THREAD

**Issue by ThakarRajesh** [cagricolak/CoreCharts#1]
i have implement in CoreCharts but my app are all orientation. orientation change then not proper bar charts display @cagricolak

**Comment by cagricolak** [comment]
thanks @thakarrajesh we will working on this issue, in the next version we will be fix it.

**Comment by cagricolak** [comment]
hi @thakarrajesh thanks for using my library,

i did the test it but i can't figure out any problem, so can you upload screen shot ? thanks.
