### ISSUE TITLE
Red Background

### ISSUE THREAD

**Issue by Buckley-James** [cagricolak/CoreCharts#4]
Hi every time I reload the chart with new data the background colour is changed to red.

It seems this cannot be overridden.

Thanks

**Comment by cagricolak** [comment]
Thanks for your feedback,i take care of.

**Comment by cagricolak** [comment]
hi @Buckley-James thanks for using my library,

you can override chart background using displayConfig property to change color.

code below:
`
barChart.displayConfig.backgroundColor = UIColor.yellow
`

hope this help.

**Comment by kemalturk** [comment]
This issue is caused by this line:
https://github.com/cagricolak/CoreCharts/blob/c6e22a945c4f87d8d15de1c3b1eca9d7c8ef21ba/CoreCharts/CoreCharts/Library/HCoreBarChart.swift#L18

We can set this color clear or white as default.
