### ISSUE TITLE
Can't change the appreance

### ISSUE THREAD

**Issue by amixpal** [cagricolak/CoreCharts#5]
Thanks for making this library. I am not able to figure it out how to change the appearance such as 'bar width', 'Bar gap'. I am using the following code in `viewDidLoad` method

    ` func initChartUI() {
        chartView.displayConfig = CoreBarChartsDisplayConfig(barWidth: 10.0,
                                                             barSpace: 10.0,
                                                             bottomSpace: 20.0,
                                                             topSpace: 20.0,
                                                             backgroundColor: UIColor.red,
                                                             titleFontSize: 12,
                                                             valueFontSize: 14,
                                                             titleFont: UIFont(),
                                                             valueFont: UIFont(),
                                                             titleLength: 12)
    }`

The output is : https://ibb.co/gvyk7Z1
How can I change the bar gap and bar width?

**Comment by cagricolak** [comment]
hi @amixpal, thanks for using my library.

CoreCharts displayConfig property is a constant so you can't change it directly at once, instead of you can change it like code below:

```
chartView.displayConfig.barSpace = 90
chartView.displayConfig.barWidth = 60
```

hope this help.
