### ISSUE TITLE
Set Background Color after Reload

### ISSUE THREAD

**Issue by TSAI-HSIAO-HAN** [cagricolak/CoreCharts#6]
Thank you for providing CoreChart for use. 
  I've tried the method you mentioned in the Red Background issue, but it didn't work. How can I fix this problem?

This is my code. I tried to add it before and after reload the data.
<img width="870" alt="螢幕快照 2019-07-30 下午6 12 23" src="https://user-images.githubusercontent.com/46244796/62121580-766c0380-b2f6-11e9-9fba-d7ba132e5fe7.png">

After reloading
<img width="291" alt="螢幕快照 2019-07-30 下午6 12 36" src="https://user-images.githubusercontent.com/46244796/62121515-56d4db00-b2f6-11e9-8859-e817419e2260.png">

**Comment by TSAI-HSIAO-HAN** [comment]
This problem seems to be caused by my simulator. Sorry for bothering you.

**Comment by cagricolak** [comment]
no problem.
