### ISSUE TITLE
y axis title

### ISSUE THREAD

**Issue by devashish11** [cagricolak/CoreCharts#7]
how to show range of numbers on y-axis like 5 then abow it 10 then 15 then 20m and so on. please reply

**Comment by cagricolak** [comment]
Sorry for late, i will check this problem this weekend stay tuned. Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cagricolak** [comment]
This is algorithmic problem, you can google it. so you can show with charts what ever you want.

**Comment by devashish11** [comment]
i have google it but i dont know where to put that code. if you can send some reference links. it would be very helpful
